name: PCK.AUTOMIC_LDAP
source: ae
binaries:
 
- object: RESOURCES/LIBS/PCK.AUTOMIC_LDAP.PRV.STORE
  resources: 
  - name: LDAPTOOL.JAR
    type: BINARY
    path: tools/ldap-tool/target/ldap-tool.jar
    version: 1.0.3
  - name: LDAPSDK.JAR
    type: BINARY
    path: tools/unboundid-ldapsdk/unboundid-ldapsdk.jar
    version: 2.3.0
  - name: LDAPSDK.SOURCE.JAR
    type: BINARY
    path: tools/unboundid-ldapsdk/unboundid-ldapsdk-2.3.0-sources.jar
    version: 2.3.0